server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankingAccount
      username: vaxidrez
      password: "VaxiDrez2005$"
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#Habilitar o Desabilitar api-docs-swagger ui
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  #paths-to-match: /controllers/**, /test/**,